# Site settings
title: Anowarul Kabir
email: akabir4@gmu.edu
description: Academic webpage of Anowarul Kabir
baseurl: "https://akabiraka.github.io/docs"
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Anowarul Kabir<br/>
  Ph.D. Candidate in Computer Science<br/>
  George Mason University

location: >
  George Mason University<br/>
  Suite 4656, 4511 Patriot Circle<br/>
  Fairfax, VA 22030

contact: >
  <a href="mailto:akabir4@gmu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact "Anowarul" via email</a> <br/>
  <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: research
  - name: collaboration
  - name: publications
  # - name: talks
  # - name: software
  # - name: team
  - name: teaching
  # - name: blogs
  - name: services
  - name: about

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Kabir
  first_name: [Anowarul]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
